apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rick-and-morty.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "rick-and-morty.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
