apiVersion: v1
kind: Service
metadata:
  name: {{ include "rick-and-morty.fullname" . }}-service
spec:
  selector:
    app: {{ include "rick-and-morty.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
  type: {{ .Values.service.type }}