apiVersion: apps/v1
kind: Deployment
metadata:
  name: rick-and-morty-app
  labels:
    app: rick-and-morty-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rick-and-morty-app
  template:
    metadata:
      labels:
        app: rick-and-morty-app
    spec:
      containers:
      - name: rick-and-morty-app
        image: david817/rick-and-morty:1.0
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: production
