name: Kubernetes Deployment and Test

on:
  push:
    branches:
      - main

jobs:
  setup-minikube:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget conntrack

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.4.0
        with:
          minikube version: 'v1.24.0'  # Latest stable version as of now
          kubernetes version: 'v1.20.2'

      - name: Start Minikube
        run: |
          minikube start --driver=docker || minikube logs

  build-and-deploy:
    needs: setup-minikube
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          eval $(minikube docker-env)
          docker build -t rick-and-morty-app .

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Wait for deployment to finish
        run: |
          kubectl rollout status deployment/rick-and-morty-app

  test-endpoints:
    needs: build-and-deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Test application endpoints
        run: |
          APP_IP=$(minikube service rick-and-morty-app --url | grep http)
          curl $APP_IP/health
          curl $APP_IP/api/v1/characters

  update-readme:
    runs-on: ubuntu-20.04
    needs: test-endpoints
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update README.md
        run: |
          echo "# Kubernetes Deployment Workflow" > README.md
          echo "This workflow sets up a small Kubernetes cluster on a GitHub Actions runner, deploys the application to the cluster, runs tests against the application's endpoints, and updates this README.md with an explanation of the workflow, jobs, and steps." >> README.md
          echo "## Jobs" >> README.md
          echo "1. **setup-minikube**: Sets up Minikube on the runner." >> README.md
          echo "2. **build-and-deploy**: Builds the Docker image and deploys it to Minikube." >> README.md
          echo "3. **test-endpoints**: Tests the application endpoints." >> README.md
          echo "4. **update-readme**: Updates the README.md file with the workflow explanation." >> README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update README.md with workflow explanation"
          git push
