name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag david817/rick-and-morty:${{ github.run_number }}
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push the Docker image
      run: docker push david817/rick-and-morty:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.5.0
      with:
        minikube version: 'latest'
        kubernetes version: 'v1.29.7'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f yamls/Deployment.yaml
        kubectl apply -f yamls/Service.yaml
        kubectl apply -f yamls/Ingress.yaml

    - name: Run tests
      run: |
        curl -f http://rickandmorty.local/healthcheck
        curl -f http://rickandmorty.local/characters
