name: Deploy to Kubernetes

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      uses: manusa/actions-setup-minikube@v2.4.0
      with:
        minikube version: 'latest'
        start-args: '--driver=docker'

    - name: Build Docker image
      run: |
        docker build -t rick-and-morty-api .
        docker tag rick-and-morty-api:latest ${{ secrets.DOCKER_HUB_USERNAME }}/rick-and-morty-api:latest
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/rick-and-morty-api:latest

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f yamls/deployment.yaml
        kubectl apply -f yamls/service.yaml
        kubectl apply -f yamls/ingress.yaml

    - name: Run tests
      run: |
        curl -f http://rick-and-morty.local/healthcheck
        curl -f http://rick-and-morty.local/characters
