name: Minikube Deployment

on:
  push:
    branches:
      - main

jobs:
  setup-minikube:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack
          VERSION="v1.24.2"
          curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-amd64.tar.gz
          sudo tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/local/bin
          rm -f crictl-$VERSION-linux-amd64.tar.gz

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          sudo minikube start --driver=none --kubernetes-version=v1.29.0

      - name: Set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Deploy Application
        run: |
          kubectl apply -f path/to/your/deployment.yaml
          kubectl apply -f path/to/your/service.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc
