
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: david817/rick-and-morty:1.0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.4.0
      with:
        minikube version: 'latest'
        kubernetes version: 'v1.21.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f yamls/Deployment.yaml
        kubectl apply -f yamls/Service.yaml
        kubectl apply -f yamls/Ingress.yaml

    - name: Run tests
      run: |
        curl -f http://rickandmorty.local/healthcheck
        curl -f http://rickandmorty.local/characters
