name: Deploy to Kubernetes

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack socat

    - name: Set up Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        minikube start --driver=docker --kubernetes-version=v1.29.7

    - name: Build Docker image
      run: |
        docker build -t david817/rick-and-morty:1.0
        docker tag rick-and-morty-api:latest ${{ secrets.DOCKER_HUB_USERNAME }}/rick-and-morty-api:latest
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/rick-and-morty-api:latest

    - name: Apply Kubernetes manifests
      run: |
        minikube kubectl -- apply -f yamls/deployment.yaml
        minikube kubectl -- apply -f yamls/service.yaml
        minikube kubectl -- apply -f yamls/ingress.yaml

    - name: Run tests
      run: |
        curl -f http://rick-and-morty.local/healthcheck
        curl -f http://rick-and-morty.local/characters
